{{- $namespace := .Release.Namespace }}
{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $service }}
  name: {{ $service }}
  namespace: {{ $namespace }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ $service }}
  type: ClusterIP
---
{{- end }}